trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  BuildConfiguration: 'Release'

steps:
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    goals: 'package'
    publishJUnitResults: false

- task: CopyFiles@2
  inputs:
    Contents: 'target/*.jar'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'

# Release via classic "Azure Web App" task in a single pipeline job (YAML)
- task: AzureWebApp@1
  inputs:
    azureSubscription: '<REPLACE_WITH_SERVICE_CONNECTION_NAME>'
    appName: 'ecom-sample-webapp'
    package: '$(Build.ArtifactStagingDirectory)/*.jar'
